name: terraform apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: terraform
jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
           terraform_version: 1.0.9

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var 'notion_api_key=${{ secrets.NOTION_API_KEY }}' -var 'notion_database_id=${{ secrets.NOTION_DATABASE_ID }}' -var 'error_notify_email=${{ secrets.EMAIL }}'

      - name: Terraform Apply
        id: apply
        run: terraform apply  -auto-approve -var 'notion_api_key=${{ secrets.NOTION_API_KEY }}' -var 'notion_database_id=${{ secrets.NOTION_DATABASE_ID }}' -var 'error_notify_email=${{ secrets.EMAIL }}'
